version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.2

    steps:
      - checkout

      # Install Poetry
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="$HOME/.poetry/bin:$PATH"

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            poetry install

      # Download trained .pth models
      - run:
          name: Download models
          command: |
            import os
            os.makedirs("./models", exist_ok=True)
            curl -o ./models/model.pth https://github.com/realvenky/cpg-detecor/releases/download/0.1.0/model.pth
            curl -o ./models/model_var_len.pth https://github.com/realvenky/cpg-detecor/releases/download/0.1.0/model_var_len.pth
      # Run tests
      - run:
          name: Run tests
          command: |
            poetry run python -m unittest discover .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
