version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.2

    steps:
      - checkout

      # Install Poetry
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="$HOME/.poetry/bin:$PATH"

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            poetry install
            
      # Download models
      - run:
          name: Download model
          command: |
            poetry run python -m utils.download
            
      # Run tests
      - run:
          name: Run tests
          command: |
            poetry run python -m unittest tests.test_cpg_pred
            poetry run python -m unittest tests.test_cpg_var_pred

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
